name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK as Non-Root User
        run: |
          # Create a non-root user 'builder' and assign ownership
          useradd -m builder
          chown -R builder:builder .
          
          - name: Build with Buildozer
      run: |
        python -m buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
